//
//  PionOneStyleKit.h
//  PionOne
//
//  Created by Qxn on 15/10/23.
//  Copyright (c) 2015 Seeed. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PionOneStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* nodePCBATargets;

// Drawing Methods
+ (void)drawNodePCBA;
+ (void)drawCanvas2;
+ (void)drawGroveButtonWithPressed: (BOOL)pressed configured: (BOOL)configured;

// Generated Images
+ (UIImage*)imageOfNodePCBA;

@end
